apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: example-app-example-app
  labels:
    heritage: Tiller
    release: example-app
    chart: example-app-0.1.0
    app: example-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-app
        release: example-app
    spec:
      containers:
        - name: example-app
          image: "atoato88/k8s-hands-on:latest"
          imagePullPolicy: IfNotPresent
          command:
          - /root/app
          - --message=Hello simple app from $(POD_IP)
          env:
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
