apiVersion: v1
kind: Service
metadata:
  labels:
    app: example-app
  name: example-app-example-app
spec:
  type: "ClusterIP"
  clusterIP: ""
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8080
  selector:
    app: example-app
