apiVersion: kubeadm.k8s.io/v1alpha3
kind: InitConfiguration
nodeRegistration:
  kubeletExtraArgs:
    cloud-provider: "gce"
    cloud-config: "/etc/gce.conf"
---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1alpha3
apiServerExtraArgs:
  cloud-provider: "gce"
  cloud-config: "/etc/kubernetes/gce.conf"
apiServerExtraVolumes:
- name: cloud
  hostPath: "/etc/gce.conf"
  mountPath: "/etc/kubernetes/gce.conf"
controllerManagerExtraArgs:
  cloud-provider: "gce"
  cloud-config: "/etc/kubernetes/gce.conf"
  cluster-cidr: "10.244.0.0/16"
  node-cidr-mask-size: "24"
  allocate-node-cidrs: "true"
controllerManagerExtraVolumes:
- name: cloud
  hostPath: "/etc/gce.conf"
  mountPath: "/etc/kubernetes/gce.conf"
